name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          INVALID_EMAIL: ${{ secrets.INVALID_EMAIL }}
          INVALID_PASSWORD: ${{ secrets.INVALID_PASSWORD }}

      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: 'index.html'
